version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.tycho:*"
        version: ">= 2.0.0"
  - package-ecosystem: "maven"
    directory: "/buildutils"
    schedule:
      interval: "daily"
